### ISSUE TITLE
Integration: Venue Map

### ISSUE THREAD

**Issue by shannonfromomaha** [omahacodeschool/lincoln-calling#158]
When front end is finished, need to integrate front end with back end.

**Comment by maedae** [comment]
**API - Google Maps**
 (Michael Todd is applying for a free-use, nonprofit license for HN -- no max hit caps)

**GEMFILE for Markers and easy embedding ** (some built-in json/js/rails functionality)
Possibility - https://github.com/apneadiving/Google-Maps-for-Rails
