### ISSUE TITLE
News/Visitors Guide...why do they look that way

### ISSUE THREAD

**Issue by shannonfromomaha** [omahacodeschool/lincoln-calling#193]
Spend some time figuring out WHY those pages look so bad.
is it bc our images are different sizes?
is it because team members stopped half way through front end integration?
is it bc they don't have full web front end functionality?

if you discover what the problem is, you don't necessarily HAVE to fix it. You can also just make a new issue and let the team know its there)

**Comment by maedae** [comment]
all layouts are implemented. 
We need to sit down and address the style issues with the news page
